In [1]:
# World Cup 2018

import pandas as pd
import json
import os


with open("C:/Users/misie/Documents/UAM/MGR_MK/open-data-master/open-data-master/data/competitions.json", "r", encoding="utf-8") as f:
    competitions = json.load(f)

df_comp = pd.DataFrame(competitions)

# filtr World Cup 2018
wc = df_comp[
    (df_comp["competition_name"] == "FIFA World Cup") &
    (df_comp["season_name"] == "2018")
]

competition_id = wc.iloc[0]["competition_id"]
season_id = wc.iloc[0]["season_id"]

print("Competition ID:", competition_id)
print("Season ID:", season_id)

Competition ID: 43
Season ID: 3

In [2]:
matches_path = f"C:/Users/misie/Documents/UAM/MGR_MK/open-data-master/open-data-master/data/matches/{competition_id}/{season_id}.json"

with open(matches_path, "r", encoding="utf-8") as f:
    matches = json.load(f)

df_matches = pd.DataFrame(matches)

print("Matches loaded:", len(df_matches))

df_matches.head()

Matches loaded: 64

,match_id,match_date,kick_off,competition,season,home_team,away_team,home_score,away_score,match_status,match_status_360,last_updated,last_updated_360,metadata,match_week,competition_stage,stadium,referee
0,8650,2018-07-06,18:00:00.000,"{'competition_id': 43, 'country_name': 'Intern...","{'season_id': 3, 'season_name': '2018'}","{'home_team_id': 781, 'home_team_name': 'Brazi...","{'away_team_id': 782, 'away_team_name': 'Belgi...",1,2,available,scheduled,2026-05-15T15:44:36.027327,2021-06-13T16:17:31.694,{'data_version': '1.0.2'},5,"{'id': 11, 'name': 'Quarter-finals'}","{'id': 4258, 'name': 'Ak Bars Arena', 'country...","{'id': 727, 'name': 'Milorad Mažić', 'country'..."
1,7584,2018-07-02,18:00:00.000,"{'competition_id': 43, 'country_name': 'Intern...","{'season_id': 3, 'season_name': '2018'}","{'home_team_id': 782, 'home_team_name': 'Belgi...","{'away_team_id': 778, 'away_team_name': 'Japan...",3,2,available,scheduled,2026-05-15T15:42:46.319084,2021-06-13T16:17:31.694,{'data_version': '1.0.2'},4,"{'id': 33, 'name': 'Round of 16'}","{'id': 256, 'name': 'Rostov Arena', 'country':...","{'id': 732, 'name': 'Malang Diedhiou', 'countr..."
2,7554,2018-06-24,12:00:00.000,"{'competition_id': 43, 'country_name': 'Intern...","{'season_id': 3, 'season_name': '2018'}","{'home_team_id': 768, 'home_team_name': 'Engla...","{'away_team_id': 798, 'away_team_name': 'Panam...",6,1,available,scheduled,2026-05-15T15:40:36.254491,2021-06-13T16:17:31.694,{'data_version': '1.0.2'},2,"{'id': 10, 'name': 'Group Stage'}","{'id': 4263, 'name': 'Stadion Nizhny Novgorod ...","{'id': 992, 'name': 'Ghead Grisha', 'country':..."
3,7539,2018-06-19,15:00:00.000,"{'competition_id': 43, 'country_name': 'Intern...","{'season_id': 3, 'season_name': '2018'}","{'home_team_id': 789, 'home_team_name': 'Polan...","{'away_team_id': 787, 'away_team_name': 'Seneg...",1,2,available,scheduled,2026-05-15T15:39:59.042458,2021-06-13T16:17:31.694,{'data_version': '1.0.2'},1,"{'id': 10, 'name': 'Group Stage'}","{'id': 4130, 'name': 'Otkritie Bank Arena', 'c...","{'id': 176, 'name': 'Nawaf Abdulla Ghayyath Sh..."
4,7550,2018-06-22,18:00:00.000,"{'competition_id': 43, 'country_name': 'Intern...","{'season_id': 3, 'season_name': '2018'}","{'home_team_id': 786, 'home_team_name': 'Serbi...","{'away_team_id': 773, 'away_team_name': 'Switz...",1,2,available,scheduled,2026-05-15T15:38:23.546532,2021-06-13T16:17:31.694,{'data_version': '1.0.2'},2,"{'id': 10, 'name': 'Group Stage'}","{'id': 4260, 'name': 'Rostec Arena', 'country'...","{'id': 186, 'name': 'Felix Brych', 'country': ..."

In [3]:
match_id = df_matches.iloc[0]["match_id"]

print("Selected match_id:", match_id)

Selected match_id: 8650

In [4]:
events_path = f"C:/Users/misie/Documents/UAM/MGR_MK/open-data-master/open-data-master/data/events/{match_id}.json"

with open(events_path, "r", encoding="utf-8") as f:
    events = json.load(f)

df_events = pd.json_normalize(events)

print("Events loaded:", df_events.shape)

Events loaded: (3589, 104)

In [5]:
df_events

,id,index,period,timestamp,minute,second,possession,duration,type.id,type.name,...,substitution.replacement.name,foul_committed.card.id,foul_committed.card.name,pass.deflected,block.deflection,shot.one_on_one,foul_committed.type.id,foul_committed.type.name,pass.goal_assist,shot.aerial_won
0,bf86711b-77f5-4a77-a475-4a8d04d92c95,1,1,00:00:00.000,0,0,1,0.000,35,Starting XI,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,9dee71fc-d07a-42ff-b449-ad1b50dcb78a,2,1,00:00:00.000,0,0,1,3.039,35,Starting XI,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,98d8a4de-e5c0-4b72-9281-14b427abbe42,3,1,00:00:00.000,0,0,1,8.013,18,Half Start,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,b2e9bc80-5920-4510-ba6e-a23f654b7cad,4,1,00:00:00.000,0,0,1,9.000,18,Half Start,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,007431ef-b210-4e34-a994-10dc91df7578,5,1,00:00:00.340,0,0,2,1.173,30,Pass,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3584,2ffa2b38-618e-489d-b5a0-5e1eb10b7977,3585,2,00:49:53.160,94,53,172,NaN,21,Foul Won,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3585,4facb795-0b4f-46f5-99ec-0d3056b5037b,3586,2,00:50:01.487,95,1,173,NaN,5,Camera On,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3586,1aba3536-1f15-403e-9379-7227152c5c72,3587,2,00:50:03.187,95,3,173,0.413,30,Pass,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3587,1283f88e-8a19-4390-906f-c0a079b559a7,3588,2,00:50:03.600,95,3,173,NaN,34,Half End,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3588,941b7605-89ae-4dfa-af50-4bebf7e7fc80,3589,2,00:50:03.600,95,3,173,NaN,34,Half End,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [6]:
lineups_path = f"C:/Users/misie/Documents/UAM/MGR_MK/open-data-master/open-data-master/data/lineups/{match_id}.json"

with open(lineups_path, "r", encoding="utf-8") as f:
    lineups = json.load(f)

print("Lineups loaded")

Lineups loaded

In [7]:
df = df_events.copy()

df["is_pass"] = df["type.name"] == "Pass"
df["is_shot"] = df["type.name"] == "Shot"
df["is_carry"] = df["type.name"] == "Carry"
df["is_duel"] = df["type.name"].isin(["Duel", "Interception"])

In [8]:


df["match_id"] = match_id  

player_match = df.groupby(
    ["match_id", "player.id", "player.name", "team.name"]
).agg(
    passes=("is_pass", "sum"),
    shots=("is_shot", "sum"),
    carries=("is_carry", "sum"),
    duels=("is_duel", "sum"),
    events=("type.name", "count")
).reset_index()

print("Player-match rows:", len(player_match))

Player-match rows: 27

In [9]:
player_match

,match_id,player.id,player.name,team.name,passes,shots,carries,duels,events
0,8650,2954.0,Youri Tielemans,Belgium,1,0,1,0,12
1,8650,3054.0,Fernando Luiz Roza,Brazil,66,1,39,3,189
2,8650,3077.0,Jan Vertonghen,Belgium,47,0,34,4,170
3,8650,3089.0,Kevin De Bruyne,Belgium,42,3,28,1,176
4,8650,3101.0,Vincent Kompany,Belgium,44,1,27,1,137
5,8650,3176.0,Thomas Meunier,Belgium,29,0,22,3,138
6,8650,3202.0,Gabriel Fernando de Jesus,Brazil,10,2,11,1,68
7,8650,3289.0,Romelu Lukaku Menama,Belgium,13,0,16,0,90
8,8650,3295.0,Thiago Emiliano da Silva,Brazil,54,1,50,1,168
9,8650,3296.0,Marouane Fellaini-Bakkioui,Belgium,35,1,25,11,193
10,8650,3472.0,Willian Borges da Silva,Brazil,20,0,19,3,83
11,8650,3501.0,Philippe Coutinho Correia,Brazil,75,6,75,5,270
12,8650,3509.0,Thibaut Courtois,Belgium,30,0,13,0,89
13,8650,3535.0,Roberto Firmino Barbosa de Oliveira,Brazil,18,2,20,1,96
14,8650,3621.0,Eden Hazard,Belgium,39,2,49,0,200
15,8650,4320.0,Neymar da Silva Santos Junior,Brazil,60,3,67,1,244
16,8650,4831.0,Nacer Chadli,Belgium,34,1,21,1,127
17,8650,5542.0,José Paulo Bezzera Maciel Júnior,Brazil,33,3,31,2,137
18,8650,5547.0,Alisson Ramsés Becker,Brazil,7,0,5,0,26
19,8650,5551.0,João Miranda de Souza Filho,Brazil,42,0,28,6,135
20,8650,5552.0,Marcelo Vieira da Silva Júnior,Brazil,80,1,63,3,245
21,8650,5553.0,Renato Soares de Oliveira Augusto,Brazil,9,2,9,0,39
22,8650,5642.0,Axel Witsel,Belgium,37,0,24,2,161
23,8650,5837.0,Douglas Costa de Souza,Brazil,19,4,27,1,81
24,8650,5838.0,Fágner Conserva Lemos,Brazil,39,0,27,4,131
25,8650,6332.0,Thomas Vermaelen,Belgium,5,0,4,1,15
26,8650,20005.0,Toby Alderweireld,Belgium,29,0,22,1,107

In [10]:

minutes = df.groupby(
    ["match_id", "player.id"]
).agg(
    minutes=("minute", "max")
).reset_index()

player_match = player_match.merge(
    minutes,
    on=["match_id", "player.id"],
    how="left"
)

In [11]:
for col in ["passes", "shots", "carries", "duels", "events"]:
    player_match[col + "_per90"] = (
        player_match[col] / player_match["minutes"] * 90
    )

In [12]:

final_columns = [
    "match_id",
    "player.id",
    "player.name",
    "team.name",
    "minutes",
    "passes_per90",
    "shots_per90",
    "carries_per90",
    "duels_per90",
    "events_per90"
]

player_match_final = player_match[final_columns]

print("\nATASET")
print(player_match_final.head())

ATASET
   match_id  player.id         player.name team.name  minutes  passes_per90  \
0      8650     2954.0     Youri Tielemans   Belgium       93      0.967742
1      8650     3054.0  Fernando Luiz Roza    Brazil       95     62.526316
2      8650     3077.0      Jan Vertonghen   Belgium       90     47.000000
3      8650     3089.0     Kevin De Bruyne   Belgium       94     40.212766
4      8650     3101.0     Vincent Kompany   Belgium       89     44.494382

   shots_per90  carries_per90  duels_per90  events_per90
0     0.000000       0.967742     0.000000     11.612903
1     0.947368      36.947368     2.842105    179.052632
2     0.000000      34.000000     4.000000    170.000000
3     2.872340      26.808511     0.957447    168.510638
4     1.011236      27.303371     1.011236    138.539326

In [13]:
print(df["minute"].max())

95

In [14]:
match_duration = df["minute"].max()

minutes = (
    df.groupby(["match_id", "player.id"])
      .agg(
          first_minute=("minute", "min"),
          last_minute=("minute", "max")
      )
      .reset_index()
)

minutes["minutes_played"] = (
    minutes["last_minute"] - minutes["first_minute"] + 1
)

minutes["minutes_played"] = minutes["minutes_played"].clip(
    upper=match_duration
)

minutes

    match_id  player.id  first_minute  last_minute  minutes_played
0       8650     2954.0            87           93               7
1       8650     3054.0             0           95              95
2       8650     3077.0             0           90              91
3       8650     3089.0             0           94              95
4       8650     3101.0             0           89              90
5       8650     3176.0             2           91              90
6       8650     3202.0             0           57              58
7       8650     3289.0             1           86              86
8       8650     3295.0             0           92              93
9       8650     3296.0             1           94              94
10      8650     3472.0             1           45              45
11      8650     3501.0             0           94              95
12      8650     3509.0             2           94              93
13      8650     3535.0            45           94              50
14      8650     3621.0             0           94              95
15      8650     4320.0             0           93              94
16      8650     4831.0             1           82              82
17      8650     5542.0             1           72              72
18      8650     5547.0             1           86              86
19      8650     5551.0             0           94              95
20      8650     5552.0             0           94              95
21      8650     5553.0            72           91              20
22      8650     5642.0             1           93              93
23      8650     5837.0            57           93              37
24      8650     5838.0             0           91              92
25      8650     6332.0            83           93              11
26      8650    20005.0             0           88              89

In [15]:
player_match = player_match.drop(
    columns=["minutes"],
    errors="ignore"
)

player_match = player_match.merge(
    minutes[
        ["match_id", "player.id", "minutes_played"]
    ],
    on=["match_id", "player.id"],
    how="left"
)

In [16]:
df["type.name"] == "Pass"

0       False
1       False
2       False
3       False
4        True
        ...
3584    False
3585    False
3586     True
3587    False
3588    False
Name: type.name, Length: 3589, dtype: bool

In [17]:
df["is_pass"] = df["type.name"] == "Pass"
df["is_shot"] = df["type.name"] == "Shot"
df["is_carry"] = df["type.name"] == "Carry"

In [18]:
passes = df[df["type.name"] == "Pass"]

In [19]:
df["completed_pass"] = (
    (df["type.name"] == "Pass") &
    (df["pass.outcome.name"].isna())
)

In [20]:
passing_stats = df.groupby(
    ["match_id", "player.id"]
).agg(
    passes_completed=("completed_pass", "sum")
).reset_index()

player_match = player_match.merge(
    passing_stats,
    on=["match_id", "player.id"],
    how="left"
)

player_match["pass_accuracy"] = (
    player_match["passes_completed"] /
    player_match["passes"]
)

In [21]:
df["shot_xg"] = df["shot.statsbomb_xg"].fillna(0)

In [22]:
xg_stats = df.groupby(
    ["match_id", "player.id"]
).agg(
    total_xg=("shot_xg", "sum")
).reset_index()

player_match = player_match.merge(
    xg_stats,
    on=["match_id", "player.id"],
    how="left"
)

In [23]:
df["is_pressure"] = (
    df["type.name"] == "Pressure"
)

pressure_stats = df.groupby(
    ["match_id", "player.id"]
).agg(
    pressures=("is_pressure", "sum")
).reset_index()

player_match = player_match.merge(
    pressure_stats,
    on=["match_id", "player.id"],
    how="left"
)

In [24]:
df["is_interception"] = (
    df["type.name"] == "Interception"
)

interception_stats = df.groupby(
    ["match_id", "player.id"]
).agg(
    interceptions=("is_interception", "sum")
).reset_index()

player_match = player_match.merge(
    interception_stats,
    on=["match_id", "player.id"],
    how="left"
)

In [25]:
per90_cols = [
    "passes",
    "shots",
    "carries",
    "duels",
    "events",
    "total_xg",
    "pressures",
    "interceptions"
]

for col in per90_cols:
    player_match[f"{col}_per90"] = (
        player_match[col] /
        player_match["minutes_played"] *
        90
    )

In [26]:
feature_columns = [
    "match_id",
    "player.id",
    "player.name",
    "team.name",

    "minutes_played",

    "passes_per90",
    "shots_per90",
    "carries_per90",
    "duels_per90",

    "pressures_per90",
    "interceptions_per90",

    "total_xg_per90",

    "pass_accuracy",

    "events_per90"
]

player_match_final = player_match[
    feature_columns
]

In [27]:
player_match_final

,match_id,player.id,player.name,team.name,minutes_played,passes_per90,shots_per90,carries_per90,duels_per90,pressures_per90,interceptions_per90,total_xg_per90,pass_accuracy,events_per90
0,8650,2954.0,Youri Tielemans,Belgium,7,12.857143,0.000000,12.857143,0.000000,90.000000,0.000000,0.000000,1.000000,154.285714
1,8650,3054.0,Fernando Luiz Roza,Brazil,95,62.526316,0.947368,36.947368,2.842105,19.894737,1.894737,0.062209,0.863636,179.052632
2,8650,3077.0,Jan Vertonghen,Belgium,91,46.483516,0.000000,33.626374,3.956044,36.593407,0.989011,0.000000,0.851064,168.131868
3,8650,3089.0,Kevin De Bruyne,Belgium,95,39.789474,2.842105,26.526316,0.947368,39.789474,0.000000,0.066543,0.785714,166.736842
4,8650,3101.0,Vincent Kompany,Belgium,90,44.000000,1.000000,27.000000,1.000000,9.000000,0.000000,0.056956,0.931818,137.000000
5,8650,3176.0,Thomas Meunier,Belgium,90,29.000000,0.000000,22.000000,3.000000,49.000000,0.000000,0.000000,0.758621,138.000000
6,8650,3202.0,Gabriel Fernando de Jesus,Brazil,58,15.517241,3.103448,17.068966,1.551724,29.482759,0.000000,0.813966,0.700000,105.517241
7,8650,3289.0,Romelu Lukaku Menama,Belgium,86,13.604651,0.000000,16.744186,0.000000,14.651163,0.000000,0.000000,0.692308,94.186047
8,8650,3295.0,Thiago Emiliano da Silva,Brazil,93,52.258065,0.967742,48.387097,0.967742,2.903226,0.967742,0.265182,0.981481,162.580645
9,8650,3296.0,Marouane Fellaini-Bakkioui,Belgium,94,33.510638,0.957447,23.936170,10.531915,60.319149,1.914894,0.075380,0.800000,184.787234
10,8650,3472.0,Willian Borges da Silva,Brazil,45,40.000000,0.000000,38.000000,6.000000,28.000000,0.000000,0.000000,0.750000,166.000000
11,8650,3501.0,Philippe Coutinho Correia,Brazil,95,71.052632,5.684211,71.052632,4.736842,12.315789,0.947368,0.319643,0.880000,255.789474
12,8650,3509.0,Thibaut Courtois,Belgium,93,29.032258,0.000000,12.580645,0.000000,0.000000,0.000000,0.000000,0.566667,86.129032
13,8650,3535.0,Roberto Firmino Barbosa de Oliveira,Brazil,50,32.400000,3.600000,36.000000,1.800000,30.600000,0.000000,0.619722,0.722222,172.800000
14,8650,3621.0,Eden Hazard,Belgium,95,36.947368,1.894737,46.421053,0.000000,18.947368,0.000000,0.167137,0.743590,189.473684
15,8650,4320.0,Neymar da Silva Santos Junior,Brazil,94,57.446809,2.872340,64.148936,0.957447,12.446809,0.000000,0.202404,0.850000,233.617021
16,8650,4831.0,Nacer Chadli,Belgium,82,37.317073,1.097561,23.048780,1.097561,34.024390,0.000000,0.025143,0.794118,139.390244
17,8650,5542.0,José Paulo Bezzera Maciel Júnior,Brazil,72,41.250000,3.750000,38.750000,2.500000,21.250000,0.000000,0.517217,0.878788,171.250000
18,8650,5547.0,Alisson Ramsés Becker,Brazil,86,7.325581,0.000000,5.232558,0.000000,0.000000,0.000000,0.000000,0.857143,27.209302
19,8650,5551.0,João Miranda de Souza Filho,Brazil,95,39.789474,0.000000,26.526316,5.684211,13.263158,0.947368,0.000000,0.928571,127.894737
20,8650,5552.0,Marcelo Vieira da Silva Júnior,Brazil,95,75.789474,0.947368,59.684211,2.842105,8.526316,1.894737,0.011134,0.825000,232.105263
21,8650,5553.0,Renato Soares de Oliveira Augusto,Brazil,20,40.500000,9.000000,40.500000,0.000000,18.000000,0.000000,1.674141,0.777778,175.500000
22,8650,5642.0,Axel Witsel,Belgium,93,35.806452,0.000000,23.225806,1.935484,42.580645,0.000000,0.000000,0.891892,155.806452
23,8650,5837.0,Douglas Costa de Souza,Brazil,37,46.216216,9.729730,65.675676,2.432432,0.000000,2.432432,0.132095,0.789474,197.027027
24,8650,5838.0,Fágner Conserva Lemos,Brazil,92,38.152174,0.000000,26.413043,3.913043,23.478261,0.978261,0.000000,0.897436,128.152174
25,8650,6332.0,Thomas Vermaelen,Belgium,11,40.909091,0.000000,32.727273,8.181818,0.000000,0.000000,0.000000,1.000000,122.727273
26,8650,20005.0,Toby Alderweireld,Belgium,89,29.325843,0.000000,22.247191,1.011236,14.157303,0.000000,0.000000,0.862069,108.202247